const { ClassCase } = require('../../helpers');

module.exports = (name) => `/**
 * ${name}.container
 *
 * (generated by rg-cli -- see https://github.com/brendanatme/rg-cli for details)
 */
import React from 'react';
import ${ClassCase(name)}Component from './${name}.component';

export default class ${ClassCase(name)} extends React.Component {
  render() {
    return (
      <${ClassCase(name)}Component {...this.props} />
    );
  }
}`;
